# ENV CONFIG

defaults: &DEFAULTS
  APP_NAME: ''
  ALLOWED_TREND: ''

  SESSION_KEY: ''
  SESSION_SECRET: ''

  GOOGLE_ANALYTICS_TRACKING_CODE: ''

  TWITTER_CONSUMER_KEY: ''
  TWITTER_CONSUMER_SECRET: ''
  TWITTER_ACCESS_TOKEN: ''
  TWITTER_ACCESS_TOKEN_SECRET: ''

  REDIS_HOST: ''
  REDIS_PORT: ''

development:
  <<: *DEFAULTS
  APP_DOMAIN: ''

test:
  <<: *DEFAULTS
  APP_DOMAIN: ''

production:
  <<: *DEFAULTS
  APP_DOMAIN: ''
